### ISSUE TITLE
Use level-0 section for page title

### ISSUE THREAD

**Issue by mojavelinux** [couchbaselabs/docs-couchbase-lite#11]
@jamiltz Can you update the AsciiDoc pages to use a level-0 section for the page (aka document) title?

```
= Compatibility Matrix
  
The table below summarizes the compatible versions of Couchbase Lite with Sync Gateway.
```

Both Antora and the UI design rely on the document starting with an H1 heading (which is what the page title becomes).

**Comment by jamiltz** [comment]
Ok! I'll get that done by the end of next week.

**Comment by jamiltz** [comment]
Actually thinking about this more, that's going to take a while to do by hand. Similarly to https://github.com/couchbaselabs/docs-couchbase-lite/issues/17, I'm not sure how to do it with a script. But if you have some tips to put me on the right path I can give it a go.

**Comment by mojavelinux** [comment]
I'll look into the possibility of doing this with script and get back to you once I assess the situation a bit more.

**Comment by mojavelinux** [comment]
PR sent for master. Shall I also submit for release/2.0 and release/1.4 as well?
