### ISSUE TITLE
Remove double comment guard from include tag lines

### ISSUE THREAD

**Issue by mojavelinux** [couchbaselabs/docs-couchbase-lite#17]
Is there a reason the include tags in the source files are double commented?

```
// # tag::getting-started[]
```

This could be simplified to:

```
// tag::getting-started[]
```

Asciidoctor doesn't require any comment characters, though obviously at least one set is needed to make it valid source code.

**Comment by jamiltz** [comment]
Oh ok thanks! I'll remove the hashtags.

**Comment by mojavelinux** [comment]
If you need me to send a PR, just let me know.

**Comment by jamiltz** [comment]
Would you do this with a script? If you have one handy I can run, that'd save me a lot of time instead of removing them by hand. Regex might do the trick but I'm not very familiar with it.

**Comment by mojavelinux** [comment]
Yep. In fact, I had a PR all ready to go, but I wanted to check first if the syntax was intentional before submitting.
