### ISSUE TITLE
Rename repository to docs-couchbase-lite

### ISSUE THREAD

**Issue by mojavelinux** [couchbaselabs/docs-couchbase-lite#21]
To align with the other new docs repositories, I propose that this repository be renamed to docs-couchbase-lite. I think it will be easier on both the team and contributors if all the repositories follow a consistent naming pattern. The same would go for https://github.com/couchbaselabs/sync-gateway-docs.

When you rename a repository, GitHub automatically routes all requests to the new name, so it won't affect anyone's workflow.

**Comment by jamiltz** [comment]
Yes sounds good, done for both repos.

**Comment by mojavelinux** [comment]
Super!
